import { Router } from "express";
import { requireAuth, requireRoles } from "../middleware/auth";
import { facultyDirectory, listMessages, sendMessage, updateCoordinators, practicePeers, listGroups, listInvitations, createGroup, inviteStudents, respondToInvitation } from "../controllers/group.controller";
const router = Router();
router.use(requireAuth);
router.get("/", requireRoles("admin", "teacher", "student"), listGroups);
router.get("/coordinators", requireRoles("admin", "teacher"), facultyDirectory);
router.get("/peers", requireRoles("student"), practicePeers);
router.get("/invitations", requireRoles("student"), listInvitations);
router.post("/", requireRoles("admin", "teacher", "student"), createGroup);
router.post("/:groupId/invitations", requireRoles("admin", "teacher", "student"), inviteStudents);
router.patch("/:groupId/invitations/me", requireRoles("student"), respondToInvitation);
router.get('/:groupId/messages', requireRoles('admin', 'teacher', 'student'), listMessages);
router.post('/:groupId/messages', requireRoles('admin', 'teacher', 'student'), sendMessage);
router.patch('/:groupId/coordinators', requireRoles('admin', 'teacher'), updateCoordinators);
export default router;
