import { Router } from 'express';
import mongoose from 'mongoose';
import { requireAuth, requireRoles } from '../middleware/auth';
import ApiError from '../utils/apiError';
import * as progress from '../controllers/readiness.controller';
import * as attempts from '../controllers/attempt.controller';
const router = Router();
router.use(requireAuth, requireRoles('admin', 'teacher', 'student'));
for (const name of ['studentId', 'assessmentId', 'ledgerId', 'attemptId']) router.param(name, (_req, _res, next, value) => next(mongoose.isValidObjectId(value) ? undefined : new ApiError(400, `Invalid ${name}`)));
const staff = requireRoles('admin', 'teacher'), student = requireRoles('student');
router.get('/policies', progress.listPolicies);
router.post('/policies', staff, progress.createPolicy);
router.get('/me', student, progress.studentReport);
router.post('/activity', student, progress.learningPulse);
router.post('/consent', student, progress.consent);
router.post('/evidence', progress.recordEvidence);
router.get('/students', staff, progress.cohortReport);
router.get('/students/:studentId', staff, progress.studentReport);
router.post('/students/:studentId/academics', staff, progress.recordAcademics);
router.post('/students/:studentId/decisions', staff, progress.recordDecision);
router.get('/assessments', student, attempts.assessmentCatalog);
router.post('/assessments/:assessmentId/start', student, attempts.startAttempt);
router.patch('/attempts/:ledgerId/:attemptId/answers', student, attempts.saveAnswers);
router.post('/attempts/:ledgerId/:attemptId/submit', student, attempts.submitAttempt);
router.get('/reviews', staff, attempts.reviewQueue);
router.post('/attempts/:ledgerId/:attemptId/review', staff, attempts.gradeAttempt);
export default router;
